version: '3.8'

services:
  backend:
    image: adrilucy/codebeginnerhub:back_sprint04
    container_name: backend_codebeginnerhub_sprint04
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:admin@mysql:3306/CodeBeginnerHub"
      JWT_SECRET: 123456

  mysql:
    image: mysql:8
    container_name: mysql_codebeginnerhub_sprint04
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CodeBeginnerHub
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: adrilucy/codebeginnerhub:front_sprint04
    container_name: frontend_codebeginnerhub_sprint04
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  mysql_data:
